#!/usr/bin/env python3
"""Post-build optimizer for the mdBook output.

Does three things to the files in `_book/`:
1. Injects <link rel="prefetch"> for every chapter page into every HTML file.
   After any page loads, the browser will prefetch all the other chapters
   during idle time, so sidebar clicks become instant.

2. Injects <link rel="preload"> hints for critical CSS/JS into every page's
   <head>, saving one round-trip on first paint.

3. Writes a service worker (sw.js) and registers it from every HTML page.
   After the first visit, all pages + assets are served from the cache — no
   network round trips at all.

Designed to be safe and idempotent: re-running on the same _book/ is a no-op
if the markers are already present.
"""
from __future__ import annotations

import os
import re
import sys
import tomllib
from pathlib import Path

BOOK_DIR = Path(os.environ.get("BOOK_DIR", "_book"))
SW_CACHE_VERSION = os.environ.get("SW_CACHE_VERSION", "paralleldevelopmentbook-v1")
MARKER = "<!-- optimize-book:injected -->"

PREFETCH_TEMPLATE = '<link rel="prefetch" href="{href}" as="document">'
PRELOAD_TEMPLATE = '<link rel="preload" href="{href}" as="{as_type}"{crossorigin}>'

# Critical resources mdBook always emits. These paths are relative to the
# site root and resolved with each page's own `<base>` or relative-to-root
# heuristic below.
CRITICAL_ASSETS = [
    ("css/general.css", "style"),
    ("css/variables.css", "style"),
    ("css/chrome.css", "style"),
    ("book.js", "script"),
]

SERVICE_WORKER_JS = """// Auto-generated by scripts/optimize-book.py
const CACHE_VERSION = '__CACHE_VERSION__';
const CACHE_SCOPE = self.registration.scope;

// Precache the entire book on install.
// The list is injected below as PRECACHE_URLS.
const PRECACHE_URLS = __PRECACHE_URLS__;

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_VERSION).then((cache) =>
      cache.addAll(PRECACHE_URLS.map((u) => new Request(u, { cache: 'reload' })))
        .catch(() => {}) // ignore individual asset failures
    )
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

// Cache-first for same-origin book assets, network-first for others.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET') return;
  if (!url.href.startsWith(CACHE_SCOPE)) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) {
        // Serve cached version immediately, refresh in background.
        fetch(event.request).then((resp) => {
          if (resp && resp.status === 200 && resp.type === 'basic') {
            caches.open(CACHE_VERSION).then((c) => c.put(event.request, resp));
          }
        }).catch(() => {});
        return cached;
      }
      return fetch(event.request).then((resp) => {
        if (resp && resp.status === 200 && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE_VERSION).then((c) => c.put(event.request, copy));
        }
        return resp;
      });
    })
  );
});
"""

SW_REGISTER_SNIPPET = """<script>
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('sw.js', { scope: './' }).catch(() => {});
  });
}
</script>"""


def repo_root_for_book_output(book_root: Path) -> Path:
    """book_root is `_book` (English) or `_book/zh` (Chinese). Return repo root."""
    if book_root.name == "zh" and book_root.parent.name == "_book":
        return book_root.parent.parent
    return book_root.parent


def book_toml_for_output(book_root: Path) -> Path:
    root = repo_root_for_book_output(book_root)
    if book_root.name == "zh":
        return root / "zh" / "book.toml"
    return root / "book.toml"


def load_site_url_prefix(book_root: Path) -> str | None:
    """Read mdBook `[output.html] site-url` and return a prefix with trailing slash.

    Used to rewrite relative `assets/*` image URLs to root-absolute paths so
    figures resolve on GitHub Pages project sites (and any host where the book
    is not served from `/`).
    """
    cfg_path = book_toml_for_output(book_root)
    if not cfg_path.is_file():
        return None
    try:
        data = tomllib.loads(cfg_path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return None
    html_cfg = data.get("output", {}).get("html", {})
    site_url = html_cfg.get("site-url", "")
    if not isinstance(site_url, str) or not site_url.strip():
        return None
    site_url = site_url.strip()
    if not site_url.endswith("/"):
        site_url += "/"
    # mdBook expects site-url to start with `/` for absolute-from-host paths.
    if not site_url.startswith("/"):
        site_url = "/" + site_url
    return site_url


def rewrite_asset_image_srcs(html: str, site_prefix: str | None) -> str:
    """Turn `<img src="assets/...">` into root-absolute paths using site_prefix."""
    if not site_prefix:
        return html
    # Avoid double-rewriting if optimize-book is re-run.
    if f'src="{site_prefix}assets/' in html or f"src='{site_prefix}assets/" in html:
        return html
    html = html.replace('src="assets/', f'src="{site_prefix}assets/')
    html = html.replace("src='assets/", f"src='{site_prefix}assets/")
    return html


def depth_to_root(html_path: Path, book_root: Path) -> str:
    """Return a relative prefix (e.g. '../') for linking from html_path to
    root. mdBook flattens all pages under _book/ at the same depth, so this
    is usually empty — but we compute it for safety in case of nested folders.
    """
    rel = html_path.parent.relative_to(book_root)
    parts = [p for p in rel.parts if p not in (".", "")]
    if not parts:
        return ""
    return "../" * len(parts)


def collect_pages(book_root: Path) -> list[Path]:
    # Sibling-edition directories (e.g. zh/) live under the top-level
    # _book/ alongside the English build. When we run the optimizer for the
    # English edition we must not reach into these sibling trees — each
    # edition has its own SUMMARY, its own prefetch set, its own service
    # worker. We hard-skip any directory that contains its own sw.js or
    # book.js (sibling mdBook output).
    pages = []
    for p in sorted(book_root.rglob("*.html")):
        # Skip print.html (single-page dump, very heavy, rarely navigated to).
        if p.name in ("print.html", "404.html"):
            continue
        # Skip inside theme/ or other generator-private folders.
        rel_parts = p.relative_to(book_root).parts
        if any(seg.startswith(".") for seg in rel_parts):
            continue
        # Skip pages belonging to a sibling edition nested under book_root.
        # Heuristic: if any ancestor below book_root contains its own book.js,
        # that ancestor is a separate mdBook build and we must not include
        # its pages in this edition's prefetch graph.
        is_sibling_edition = False
        ancestor = p.parent
        while ancestor != book_root and ancestor != ancestor.parent:
            if (ancestor / "book.js").exists() and ancestor != book_root:
                is_sibling_edition = True
                break
            ancestor = ancestor.parent
        if is_sibling_edition:
            continue
        pages.append(p)
    return pages


def build_prefetch_links(current: Path, pages: list[Path], book_root: Path) -> str:
    links = []
    current_abs = current.resolve()
    for p in pages:
        if p.resolve() == current_abs:
            continue
        rel = os.path.relpath(p, current.parent)
        links.append(PREFETCH_TEMPLATE.format(href=rel))
    return "\n    ".join(links)


def build_preload_links(prefix: str) -> str:
    links = []
    for path, as_type in CRITICAL_ASSETS:
        crossorigin = ""
        if as_type == "font":
            crossorigin = " crossorigin"
        links.append(
            PRELOAD_TEMPLATE.format(
                href=f"{prefix}{path}", as_type=as_type, crossorigin=crossorigin
            )
        )
    return "\n    ".join(links)


def inject_into_html(html: str, prefetch_block: str, preload_block: str) -> str | None:
    if MARKER in html:
        return None  # already injected, idempotent no-op

    head_close = html.find("</head>")
    if head_close == -1:
        return None  # malformed, skip

    injection = (
        f"\n    {MARKER}\n"
        f"    {preload_block}\n"
        f"    {prefetch_block}\n"
        f"    {SW_REGISTER_SNIPPET}\n"
    )
    return html[:head_close] + injection + html[head_close:]


def generate_service_worker(book_root: Path, pages: list[Path]) -> None:
    precache = []
    # Cache root pages.
    for p in pages:
        rel = p.relative_to(book_root).as_posix()
        precache.append(f"./{rel}")
    # Cache critical assets.
    for path, _ in CRITICAL_ASSETS:
        precache.append(f"./{path}")
    # Also cache a handful of mdBook-generated assets if present.
    extras = [
        "highlight.css",
        "tomorrow-night.css",
        "ayu-highlight.css",
        "favicon.svg",
        "favicon.png",
        "searchindex.json",
        "searchindex.js",
        "searcher.js",
        "clipboard.min.js",
        "elasticlunr.min.js",
        "mark.min.js",
    ]
    for extra in extras:
        if (book_root / extra).exists():
            precache.append(f"./{extra}")

    assets_dir = book_root / "assets"
    if assets_dir.is_dir():
        for svg in sorted(assets_dir.glob("*.svg")):
            rel = svg.relative_to(book_root).as_posix()
            precache.append(f"./{rel}")

    precache_urls_literal = "[" + ", ".join(f'"{u}"' for u in precache) + "]"
    sw_content = SERVICE_WORKER_JS.replace("__PRECACHE_URLS__", precache_urls_literal)
    sw_content = sw_content.replace("__CACHE_VERSION__", SW_CACHE_VERSION)
    (book_root / "sw.js").write_text(sw_content, encoding="utf-8")


def main() -> int:
    book_root = BOOK_DIR.resolve()
    if not book_root.exists():
        print(f"error: {book_root} does not exist — run `mdbook build` first", file=sys.stderr)
        return 1

    pages = collect_pages(book_root)
    if not pages:
        print("error: no HTML pages found in _book/", file=sys.stderr)
        return 1

    print(f"optimize-book: {len(pages)} pages found in {book_root}/")

    site_prefix = load_site_url_prefix(book_root)
    if site_prefix:
        print(f"optimize-book: site-url prefix {site_prefix!r} — rewriting asset image srcs")

    modified = 0
    skipped = 0
    for page in pages:
        html = page.read_text(encoding="utf-8")
        html = rewrite_asset_image_srcs(html, site_prefix)
        prefix = depth_to_root(page, book_root)
        prefetch_block = build_prefetch_links(page, pages, book_root)
        preload_block = build_preload_links(prefix)
        new_html = inject_into_html(html, prefetch_block, preload_block)
        if new_html is None:
            skipped += 1
            continue
        page.write_text(new_html, encoding="utf-8")
        modified += 1

    # Single-page print build is excluded from collect_pages; still fix figure paths.
    print_html = book_root / "print.html"
    if print_html.is_file():
        ph = print_html.read_text(encoding="utf-8")
        ph2 = rewrite_asset_image_srcs(ph, site_prefix)
        if ph2 != ph:
            print_html.write_text(ph2, encoding="utf-8")

    generate_service_worker(book_root, pages)
    sw_kb = (book_root / "sw.js").stat().st_size / 1024

    print(f"optimize-book: injected into {modified} pages (skipped {skipped})")
    print(f"optimize-book: wrote sw.js ({sw_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
